export const messageConstants = {
    CREATE_MESSAGE_REQUEST: "CREATE_MESSAGE_REQUEST",
    CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
    CREATE_MESSAGE_FAILURE: "CREATE_MESSAGE_FAILURE",

    GET_MESSAGE_REQUEST: "GET_MESSAGE_REQUEST",
    GET_MESSAGE_SUCCESS: "GET_MESSAGE_SUCCESS",
    GET_MESSAGE_FAILURE: "GET_MESSAGE_FAILURE",

    SET_TYPING_REQUEST: "SET_TYPING_REQUEST",
    SET_TYPING_SUCCESS: "SET_TYPING_SUCCESS",
    SET_TYPING_FAILURE: "SET_TYPING_FAILURE",

    LISTEN_TYPING_REQUEST: "LISTEN_TYPING_REQUEST",
    LISTEN_TYPING_SUCCESS: "LISTEN_TYPING_SUCCESS",
    LISTEN_TYPING_FAILURE: "LISTEN_TYPING_FAILURE"
}