export const userConstants = {
    CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",

    GET_ADMIN_REQUEST: "GET_ADMIN_REQUEST",
    GET_ADMIN_SUCCESS: "GET_ADMIN_SUCCESS",
    GET_ADMIN_FAILURE: "GET_ADMIN_FAILURE",

    LIST_USERS_REQUEST: "LIST_USERS_REQUEST",
    LIST_USERS_SUCCESS: "LIST_USERS_SUCCESS",
    LIST_USERS_FAILURE: "LIST_USERS_FAILURE",
}